### ISSUE TITLE
Favorite team

### ISSUE THREAD

**Issue by d-kar** [MLBAMGames/NHLGames#122]
Add a favorite team option.

- Show first in the list of today's games
- Highlight days in calendar when your team is playing
- Option to hide spoilers only for favorite team

**Comment by d-kar** [comment]
Same request on reddit:
https://www.reddit.com/r/nhl_games/comments/7emujt/select_favourite_team/

**Comment by murko69** [comment]
Even though it seems to be an old request I wanted to second it.
I do like the short list of features suggested in the first post, but just wanna say that I would rather have favorite **teams** rather than just the one. 
I don't really have a hard core favorite team in the NHL - I rather like to watch games with my favorite Swedish players in them.
Right now that makes me wanna add the Caps, Preds and Ducks to a setting like that :)
