### ISSUE TITLE
Add an option to login with valid NHL/Rogers account to watch games

### ISSUE THREAD

**Issue by d-kar** [MLBAMGames/NHLGames#31]
Since MLBAM patched a hole (I hope temporally) it would be nice to be able to use this app if you have a valid gamecenter subscription.

**Comment by jwallet** [comment]
not sure if people trust this app enough to enter their paid account infos into a text field

**Comment by d-kar** [comment]
It's open source though.
I had a Kodi add-on which I used and gave it my paid account info. Didn't have any problems with it.

**Comment by d-kar** [comment]
This feature would be useful because nhl game center web is bad imo and I'd rather use this app instead. (Hell, I have an access as a Rogers subscribes, but still using this app)

**Comment by NHLGames** [comment]
If you're already paying for a subscription, isn't that already ethical justification enough to use this app? :P Although I suppose if they patch the backdoor the legitimate login would still work in theory

**Comment by d-kar** [comment]
Yup, I don't have ethical problem using this app :)
Just want to be able to use it in case they patch the hole.

**Comment by jwallet** [comment]
correct me if i'm wrong, some people think if we add this they will be able to have the same streams that we provide, using their account won't get them ban since it's a one user use, but it will show that their connection comes from their real location because the app will have to remove the hosts entry to use the account credentials. and it will require some refact to let this option get streams as well but in a legit way

**Comment by jwallet** [comment]
since we added the proxy this feature may be easier to add
