### ISSUE TITLE
Virus detected in zip file

### ISSUE THREAD

**Issue by AwesomeAL** [MLBAMGames/NHLGames#319]
Trojan:Script/Oneeva.A!ml was detected by windows 10 defender in NHLGames-v.1.6.3-complete.zip

**Comment by zaschiff** [comment]
A friend of mine got a similar warning; his Win 10 defender stated it was Program:Win32/Uwamson.A!ml. Is this going to get fixed?

**Comment by jwallet** [comment]
you can build the source code from this repo (check Code tab) if you don't trust the build we released. we did not add any virus to the app, I don't even know why I have to tell you that. But if you don't want to run the app because of this warning and can't whitelist the app, well I guess not using it, is the good call here.
